### ISSUE TITLE
add sudo please

### ISSUE THREAD

**Issue by tonghuikang** [tlkh/setup-cheatsheets#2]
https://github.com/tlkh/setup-cheatsheets/blob/8c6d6b95aa2c0b34fd0fc17afaa10a6cf5f62d25/cuda_gcp.sh#L20

**Comment by tonghuikang** [comment]
hkmac@image-service-hk:~$ jupyter nbextension enable --py widgetsnbextension --sys-prefix
Enabling notebook extension jupyter-js-widgets/extension...
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 386, in _set_nbextension_state_python
    for nbext in nbexts]
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 386, in <listcomp>
    for nbext in nbexts]
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 351, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "/usr/local/lib/python3.5/dist-packages/notebook/config_manager.py", line 136, in update
    self.set(section_name, data)
  File "/usr/local/lib/python3.5/dist-packages/notebook/config_manager.py", line 110, in set
    self.ensure_config_dir_exists()
  File "/usr/local/lib/python3.5/dist-packages/notebook/config_manager.py", line 67, in ensure_config_dir_exists
    os.makedirs(self.config_dir, 0o755)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/etc'

**Comment by tlkh** [comment]
Yah I realised also but I never bothered
